language: node_js
node_js:
  - 12

script:
  - npm run version
  - npm run build
  - npm run validate
  - npm run documentation
  - touch docs/.nojekyll

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: eric@kidderberg.us
    api_key: $NPM_API_KEY
    on:
      tags: true

notifications:
  email:
    on_failure: change
    on_success: change
